"""add grade scale model for percentage ranges

Revision ID: 0daea3fab2f1
Revises: e0c436ee07e0
Create Date: 2026-01-06 10:55:37.676856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daea3fab2f1'
down_revision = 'e0c436ee07e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_letter', sa.String(length=10), nullable=False),
    sa.Column('min_percentage', sa.Float(), nullable=False),
    sa.Column('max_percentage', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_scale')
    # ### end Alembic commands ###
